package io.torvox.ui

import android.content.Context
import android.util.AttributeSet
import android.view.SurfaceHolder
import android.view.SurfaceView

/**
 * SurfaceView that hosts the Rust wgpu rendering pipeline.
 * Manages the Surface lifecycle and passes ANativeWindow to Rust.
 *
 * The Rust bridge (TorvoxBridge) is generated by UniFFI at build time.
 * After running `cargo build -p torvox-gui-android` + `uniffi-bindgen generate`,
 * the bridge types will be available in `io.torvox.bridge`.
 */
class TerminalSurface
    @JvmOverloads
    constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyleAttr: Int = 0,
    ) : SurfaceView(context, attrs, defStyleAttr),
        SurfaceHolder.Callback {
        private var bridge: Any? = null // TorvoxBridge (UniFFI generated)
        private var rows: Int = 24
        private var cols: Int = 80

        init {
            holder.addCallback(this)
            isFocusable = true
            isFocusableInTouchMode = true
        }

        fun initialize(bridgeInstance: Any) {
            this.bridge = bridgeInstance
        }

        fun setDimensions(
            rows: Int,
            cols: Int,
        ) {
            this.rows = rows
            this.cols = cols
        }

        override fun surfaceCreated(holder: SurfaceHolder) {
            // Pass ANativeWindow pointer to Rust bridge
            // Bridge must be initialized before surface creation
        }

        override fun surfaceChanged(
            holder: SurfaceHolder,
            format: Int,
            width: Int,
            height: Int,
        ) {
            // Notify Rust of size change
        }

        override fun surfaceDestroyed(holder: SurfaceHolder) {
            // Release Rust surface resources
        }

        fun requestRender() {
            // Trigger Rust render cycle
        }

        fun getBridge(): Any? = bridge
    }
