name: Rust Checks
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
permissions:
  contents: read
jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/kudzu
          path: result-kudzu
      - uses: ./result-kudzu/.github/actions/install-nix
      - uses: cachix/cachix-action@master
        continue-on-error: true
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          rm -f ~/.config/nix/nix.conf
          scripts/check-rust.nu --full --fuzz
      - uses: actions/upload-artifact@main
        if: always()
        with:
          name: nextest-logs
          path: |
            target/nextest/default/
            target/nextest/ci/
